import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

enum AppLocale {
  uzLatin(
    Locale.fromSubtags(
      languageCode: 'uz',
      scriptCode: 'Latn',
      countryCode: 'UZ',
    ),
    'UZ',
  ),
  uzCyrillic(
    Locale.fromSubtags(
      languageCode: 'uz',
      scriptCode: 'Cyrl',
      countryCode: 'UZ',
    ),
    'Кир',
  ),
  ru(Locale('ru', 'RU'), 'RU');

  const AppLocale(this.locale, this.label);

  final Locale locale;
  final String label;
}

class AppLocalizations {
  AppLocalizations(this.appLocale);

  final AppLocale appLocale;

  static List<Locale> get supportedLocales =>
      AppLocale.values.map((item) => item.locale).toList(growable: false);

  static const _localizedValues = <AppLocale, Map<String, String>>{
    AppLocale.uzLatin: {
      'appName': 'Yo\'lovchi',
      'authTitle': 'Premium taksi & delivery tajribasi',
      'authSubtitle':
          'Eng qulay va xavfsiz transport xizmatlari bitta ilovada.',
      'loginTitle': 'Kirish',
      'registerTitle': 'Ro‘yxatdan o‘tish',
      'phoneNumber': 'Telefon raqami',
      'password': 'Parol',
      'forgotPassword': 'Parolni unutdingizmi?',
      'passwordRecoveryMock': 'Demo rejim: parolni tiklash faollashtirilmagan.',
      'continue': 'Davom etish',
      'fullName': 'To‘liq ism',
      'confirmPassword': 'Parolni tasdiqlang',
      'createAccount': 'Hisob yaratish',
      'passwordMismatch': 'Parollar mos kelmadi',
      'unexpectedError':
          'Kutilmagan xatolik yuz berdi. Iltimos, qayta urinib ko‘ring.',
      'needAccount': 'Hisobingiz yo‘qmi? ',
      'registerNow': 'Ro‘yxatdan o‘ting',
      'haveAccount': 'Allaqachon hisobingiz bormi? ',
      'loginInstead': 'Kirish',
      'changePassword': 'Parolni o‘zgartirish',
      'oldPassword': 'Eski parol',
      'newPassword': 'Yangi parol',
      'confirmNewPassword': 'Yangi parolni tasdiqlang',
      'passwordUpdated': 'Parol muvaffaqiyatli yangilandi',
      'save': 'Saqlash',
      'refresh': 'Yangilash',
      'notifications': 'Bildirishnomalar',
      'homeGreeting': 'Assalomu alaykum!',
      'ratingWithValue': 'Reyting: {rating}',
      'orderTaxi': 'Taksi buyurtma qilish',
      'sendDelivery': 'Yuk jo‘natish',
      'activeOrders': 'Faol buyurtmalar',
      'noActiveOrders': 'Hozircha faol buyurtmalar yo‘q. Yangi zakaz yarating!',
      'recentOrders': 'So‘nggi buyurtmalar',
      'taxiOrder': 'Taksi',
      'deliveryOrder': 'Delivery',
      'status_pending': 'Kutilmoqda',
      'status_active': 'Yo‘lda',
      'status_completed': 'Yakunlandi',
      'status_cancelled': 'Bekor qilindi',
      'phoneNumberShort': 'Tel',
      'editProfile': 'Profilni tahrirlash',
      'changePhoto': 'Profil rasmini yangilash',
      'refreshProfile': 'Profilni yangilash',
      'selectImage': 'Galereyadan tanlash',
      'noImageSelected': 'Surat tanlanmagan',
      'uploadPhoto': 'Rasmni yuklash',
      'photoUpdated': 'Profil rasmi yangilandi',
      'language': 'Til',
      'darkMode': 'Tungi rejim',
      'darkModeDescription': 'Interfeysni qorong‘i temaga o‘tkazing',
      'driverMode': 'Haydovchi rejimi',
      'driverModeDescription':
          'Buyurtmalarni qabul qilib, daromad oling. Tasdiqlashdan so‘ng, haydovchilar paneli faollashadi.',
      'switchToDriver': 'Haydovchi paneliga o‘tish',
      'applicationPending': 'Ariza ko‘rib chiqilmoqda',
      'becomeDriver': 'Haydovchi bo‘lish',
      'driverBalance': 'Hisobingiz: {balance} so‘m',
      'logout': 'Chiqish',
      'home': 'Bosh sahifa',
      'orders': 'Buyurtmalar',
      'profile': 'Profil',
      'ordersTitle': 'Buyurtmalar',
      'activeTab': 'Faol',
      'historyTab': 'Tarix',
      'noHistory': 'Tarix bo‘sh. Yangi buyurtma yarating!',
      'orderDetails': 'Buyurtma tafsilotlari',
      'fromLocation': 'Jo‘natish manzili',
      'toLocation': 'Borish manzili',
      'price': 'Narx',
      'cancelReason': 'Bekor qilish sababi',
      'cancelledByUser': 'Foydalanuvchi tomonidan bekor qilindi',
      'orderCancelled': 'Buyurtma bekor qilindi',
      'cancelOrder': 'Buyurtmani bekor qilish',
      'pickupLocation': 'Manzil (jo‘natish)',
      'pickupAddress': 'Aniq manzil (xarita)',
      'dropoffAddress': 'Borish manzili (xarita)',
      'region': 'Viloyat',
      'district': 'Tuman / shahar',
      'dropLocation': 'Manzil (borish)',
      'tapToPickOnMap': 'Xaritadan tanlash uchun bosing',
      'detectingLocation': 'Joylashuv aniqlanmoqda...',
      'passengers': 'Yo‘lovchilar soni',
      'fullCar': 'To‘liq mashina',
      'passengersCount': '{count} yo‘lovchi',
      'date': 'Sana',
      'timeRange': 'Vaqt oralig‘i',
      'scheduledTime': 'Rejalashtirilgan vaqt',
      'optionalNote': 'Qo‘shimcha eslatma',
      'noteHint': 'Masalan: Haydovchi kelganda qo‘ng‘iroq qiling',
      'estimatedPrice': 'Taxminiy narx',
      'fillInfoForPrice': 'Narxni ko‘rish uchun barcha maydonlarni to‘ldiring',
      'priceUnspecified': 'Aniqlanmagan',
      'confirmOrder': 'Buyurtmani tasdiqlash',
      'orderSummary': 'Buyurtma xulosasi',
      'note': 'Eslatma',
      'noNote': 'Eslatma qo‘shilmagan',
      'sendOrder': 'Buyurtmani yuborish',
      'orderSentTitle': 'Buyurtma yuborildi',
      'orderSentDescription':
          'Operatorlarimiz tez orada siz bilan bog‘lanadi. Rahmat!',
      'pickOnMap': 'Xaritadan tanlash',
      'selectedAddress': 'Tanlangan manzil',
      'searchingAddress': 'Manzil aniqlanmoqda...',
      'confirmLocation': 'Manzilni tasdiqlash',
      'useCurrentLocation': 'Joriy joylashuvni ol',
      'locationPermissionDenied': 'Joylashuv ruxsatini berishingiz kerak',
      'locationUnavailable': 'Joylashuvni aniqlab bo‘lmadi',
      'enableLocationServices': 'Qurilmada joylashuv xizmatlarini yoqing',
      'orderId': 'Buyurtma raqami',
      'backHome': 'Bosh sahifaga qaytish',
      'senderInfo': 'Jo‘natuvchi ma’lumoti',
      'receiverInfo': 'Qabul qiluvchi ma’lumoti',
      'receiverPhone': 'Qabul qiluvchi telefoni',
      'packageType': 'Yuk turi',
      'document': 'Hujjat',
      'box': 'Quti',
      'luggage': 'Bagaj',
      'valuable': 'Qimmatbaho',
      'other': 'Boshqa',
      'confirmDelivery': 'Yetkazib berishni tasdiqlash',
      'deliverySummary': 'Yetkazib berish xulosasi',
      'sender': 'Jo‘natuvchi',
      'receiver': 'Qabul qiluvchi',
      'deliverySentTitle': 'Yuk jo‘natildi',
      'deliverySentDescription':
          'Buyurtmangiz haydovchilarga yuborildi. Holatini kuzatib boring.',
      'driverApplication': 'Haydovchi arizasi',
      'driverApplicationSubtitle':
          'Quyidagi ma’lumotlarni to‘ldirib, haydovchi bo‘lishingiz mumkin.',
      'carModel': 'Avtomobil modeli',
      'carNumber': 'Davlat raqami',
      'driverLicenseUpload': 'Haydovchilik guvohnomasi nusxasi',
      'mockUploadSuccess': 'Mo‘ljal uchun fayl yuklandi (demo).',
      'uploadPlaceholder': 'Faylni yuklash',
      'submitApplication': 'Arizani yuborish',
      'fillAllFields': 'Barcha maydonlarni to‘ldiring',
      'applicationSentTitle': 'Ariza yuborildi',
      'applicationSentDescription':
          'Biz arizangizni qabul qildik. 1-2 daqiqada tasdiqlanadi.',
      'driverDashboard': 'Haydovchi paneli',
      'currentBalance': 'Joriy balans',
      'withdraw': 'Pul yechish',
      'todayStats': 'Bugungi natijalar',
      'ordersCount': '{count} ta buyurtma',
      'monthStats': 'Oylik natijalar',
      'incomingOrders': 'Kelayotgan buyurtmalar',
      'newTaxiOrders': 'Yangi taksi buyurtmalari',
      'newDeliveryOrders': 'Yangi delivery buyurtmalari',
      'orderHistory': 'Buyurtmalar tarixi',
      'noPendingOrders': 'Hozircha yangi buyurtmalar yo‘q.',
      'noActiveDriverOrders': 'Faol buyurtmalar yo‘q.',
      'viewHistory': 'Tarixni ko‘rish',
      'withdrawMock': 'Demo rejim: balansdan pul yechish imkoni yo‘q.',
      'close': 'Yopish',
      'completedOrders': 'Yakunlangan buyurtmalar',
      'acceptTimer': 'Qabul qilish uchun qolgan vaqt: {time}',
      'acceptOrder': 'Buyurtmani qabul qilish',
      'orderAccepted': 'Buyurtma qabul qilindi',
      'completeOrder': 'Buyurtmani yakunlash',
      'orderCompleted': 'Buyurtma yakunlandi',
      'orderExpired': 'Buyurtma muddati tugadi',
      'orderIdLabel': 'Buyurtma raqami: {id}',
      'markAllRead': 'Barchasini o‘qilgan deb belgilash',
      'notifDriverApplication': 'Haydovchi arizangiz qabul qilindi.',
      'notifDriverApproved':
          'Tabriklaymiz! Haydovchi sifatida tasdiqlandingiz.',
    },
    AppLocale.uzCyrillic: {
      'appName': 'Йўловчи',
      'authTitle': 'Премиум такси ва етказиб бериш',
      'authSubtitle':
          'Энг қулай ва хавфсиз транспорт хизматлари битта иловада.',
      'loginTitle': 'Кириш',
      'registerTitle': 'Рўйхатдан ўтиш',
      'phoneNumber': 'Телефон рақами',
      'password': 'Парол',
      'forgotPassword': 'Паролни унутдингизми?',
      'passwordRecoveryMock': 'Демо режими: паролни тиклаш мавжуд эмас.',
      'continue': 'Давом этиш',
      'fullName': 'Тўлиқ исм',
      'confirmPassword': 'Паролни тасдиқланг',
      'createAccount': 'Аккаунт яратиш',
      'passwordMismatch': 'Пароллар мос келмади',
      'unexpectedError':
          'Кутилмаган хатолик юз берди. Илтимос, қайта уриниб кўринг.',
      'needAccount': 'Аккаунтингиз йўқми? ',
      'registerNow': 'Рўйхатдан ўтинг',
      'haveAccount': 'Аккаунтингиз борми? ',
      'loginInstead': 'Кириш',
      'changePassword': 'Паролни ўзгартириш',
      'oldPassword': 'Эски парол',
      'newPassword': 'Янги парол',
      'confirmNewPassword': 'Янги паролни тасдиқланг',
      'passwordUpdated': 'Парол муваффақиятли янгиланди',
      'save': 'Сақлаш',
      'refresh': 'Янгилаш',
      'notifications': 'Билдиришномалар',
      'homeGreeting': 'Ассалому алайкум!',
      'ratingWithValue': 'Рейтинг: {rating}',
      'orderTaxi': 'Такси чақириш',
      'sendDelivery': 'Юк жўнатиш',
      'activeOrders': 'Фаол буюртмалар',
      'noActiveOrders': 'Ҳозирча фаол буюртмалар йўқ. Янги буюртма яратинг!',
      'recentOrders': 'Сўнгги буюртмалар',
      'taxiOrder': 'Такси',
      'deliveryOrder': 'Деливери',
      'status_pending': 'Кутилмоқда',
      'status_active': 'Йўлда',
      'status_completed': 'Якунланди',
      'status_cancelled': 'Бекор қилинди',
      'phoneNumberShort': 'Тел',
      'editProfile': 'Профилни таҳрирлаш',
      'changePhoto': 'Профил расмини янгилаш',
      'refreshProfile': 'Профилни янгилаш',
      'selectImage': 'Галереядан танлаш',
      'noImageSelected': 'Расм танланмаган',
      'uploadPhoto': 'Расмни юклаш',
      'photoUpdated': 'Профил расми янгиланди',
      'language': 'Тил',
      'darkMode': 'Тунги режим',
      'darkModeDescription': 'Интерфейсни қоронғи мавзусига ўтказинг',
      'driverMode': 'Ҳайдовчи режими',
      'driverModeDescription':
          'Буюртмаларни қабул қилиб даромад олинг. Тасдиқдан сўнг панел фаол бўлади.',
      'switchToDriver': 'Ҳайдовчи панелига ўтиш',
      'applicationPending': 'Ариза кўриб чиқилмоқда',
      'becomeDriver': 'Ҳайдовчи бўлиш',
      'driverBalance': 'Ҳисобингиз: {balance} сўм',
      'logout': 'Чиқиш',
      'home': 'Бош саҳифа',
      'orders': 'Буюртмалар',
      'profile': 'Профил',
      'ordersTitle': 'Буюртмалар',
      'activeTab': 'Фаол',
      'historyTab': 'Тарих',
      'noHistory': 'Тарих бўш. Янги буюртма яратинг!',
      'orderDetails': 'Буюртма тафсилотлари',
      'fromLocation': 'Жўнатиш манзили',
      'toLocation': 'Бориш манзили',
      'price': 'Нарх',
      'cancelReason': 'Бекор қилиш сабаби',
      'cancelledByUser': 'Фойдаланувчи бекор қилди',
      'orderCancelled': 'Буюртма бекор қилинди',
      'cancelOrder': 'Буюртмани бекор қилиш',
      'pickupLocation': 'Манзил (жўнатиш)',
      'pickupAddress': 'Аниқ манзил (харита)',
      'dropoffAddress': 'Бориш манзили (харита)',
      'region': 'Вилоят',
      'district': 'Туман / шаҳар',
      'dropLocation': 'Манзил (бориш)',
      'tapToPickOnMap': 'Харитадан танлаш учун босинг',
      'detectingLocation': 'Жойлашув аниқланмоқда...',
      'passengers': 'Йўловчилар сони',
      'fullCar': 'Тўлиқ машина',
      'passengersCount': '{count} йўловчи',
      'date': 'Сана',
      'timeRange': 'Вақт оралиғи',
      'scheduledTime': 'Режалаштирилган вақт',
      'optionalNote': 'Қўшимча эслатма',
      'noteHint': 'Масалан: Ҳайдовчи келганда қўнғироқ қилинг',
      'estimatedPrice': 'Тахминий нарх',
      'fillInfoForPrice': 'Нархни кўриш учун маълумотларни киритинг',
      'priceUnspecified': 'Аниқланмаган',
      'confirmOrder': 'Буюртмани тасдиқлаш',
      'orderSummary': 'Буюртма хулосаси',
      'note': 'Эслатма',
      'noNote': 'Эслатма қўшилмаган',
      'sendOrder': 'Буюртмани юбориш',
      'orderSentTitle': 'Буюртма юборилди',
      'orderSentDescription':
          'Операторларимиз тез орада сиз билан боғланади. Раҳмат!',
      'pickOnMap': 'Харитадан танлаш',
      'selectedAddress': 'Танланган манзил',
      'searchingAddress': 'Манзил аниқланмоқда...',
      'confirmLocation': 'Манзилни тасдиқлаш',
      'useCurrentLocation': 'Жорий жойлашувни олиш',
      'locationPermissionDenied': 'Жойлашув рухсатини беринг',
      'locationUnavailable': 'Жойлашувни аниқлаб бўлмади',
      'enableLocationServices': 'Қурилмада жойлашув хизматларини ёқинг',
      'orderId': 'Буюртма рақами',
      'backHome': 'Бош саҳифа',
      'senderInfo': 'Жўнатувчи маълумоти',
      'receiverInfo': 'Қабул қилувчи маълумоти',
      'receiverPhone': 'Қабул қилувчи телефони',
      'packageType': 'Юк тури',
      'document': 'Ҳужжат',
      'box': 'Қути',
      'luggage': 'Багаж',
      'valuable': 'Қимматбахо',
      'other': 'Бошқа',
      'confirmDelivery': 'Етказиб беришни тасдиқлаш',
      'deliverySummary': 'Етказиб бериш хулосаси',
      'sender': 'Жўнатувчи',
      'receiver': 'Қабул қилувчи',
      'deliverySentTitle': 'Юк жўнатилди',
      'deliverySentDescription':
          'Буюртмангиз ҳайдовчиларга юборилди. Ҳолатини кузатинг.',
      'driverApplication': 'Ҳайдовчи аризаси',
      'driverApplicationSubtitle':
          'Қуйидаги маълумотларни тўлдириб, ҳайдовчи бўлишингиз мумкин.',
      'carModel': 'Автомобиль модели',
      'carNumber': 'Давлат рақами',
      'driverLicenseUpload': 'Ҳайдовчилик гувоҳномаси нусхаси',
      'mockUploadSuccess': 'Намуна учун файл юкланди (демо).',
      'uploadPlaceholder': 'Файл юклаш',
      'submitApplication': 'Аризани юбориш',
      'fillAllFields': 'Барча майдонларни тўлдиринг',
      'applicationSentTitle': 'Ариза юборилди',
      'applicationSentDescription':
          'Аризангизни қабул қилдик. Бир неча дақиқа ичида тасдиқланади.',
      'driverDashboard': 'Ҳайдовчи панели',
      'currentBalance': 'Жорий баланс',
      'withdraw': 'Пул ечиш',
      'todayStats': 'Бугунги натижалар',
      'ordersCount': '{count} та буюртма',
      'monthStats': 'Ойлик натижалар',
      'incomingOrders': 'Келиб тушган буюртмалар',
      'newTaxiOrders': 'Янги такси буюртмалари',
      'newDeliveryOrders': 'Янги деливери буюртмалари',
      'orderHistory': 'Буюртмалар тарихи',
      'noPendingOrders': 'Ҳозирча янги буюртмалар йўқ.',
      'noActiveDriverOrders': 'Фаол буюртмалар йўқ.',
      'viewHistory': 'Тарихни кўриш',
      'withdrawMock': 'Демо режим: балансдан пул ечиб бўлмайди.',
      'close': 'Ёпиш',
      'completedOrders': 'Якунланган буюртмалар',
      'acceptTimer': 'Қабул қилиш учун қолган вақт: {time}',
      'acceptOrder': 'Буюртмани қабул қилиш',
      'orderAccepted': 'Буюртма қабул қилинди',
      'completeOrder': 'Буюртмани якунлаш',
      'orderCompleted': 'Буюртма якунланди',
      'orderExpired': 'Буюртма муддати тугади',
      'orderIdLabel': 'Буюртма рақами: {id}',
      'markAllRead': 'Ҳаммасини ўқилган деб белгилаш',
      'notifDriverApplication': 'Ҳайдовчи аризангиз қабул қилинди.',
      'notifDriverApproved': 'Табриклаймиз! Ҳайдовчи сифатида тасдиқландингиз.',
    },
    AppLocale.ru: {
      'appName': 'Пассажир',
      'authTitle': 'Премиум‑сервис такси и доставки',
      'authSubtitle': 'Лучшие поездки и курьерские услуги в одном приложении.',
      'loginTitle': 'Вход',
      'registerTitle': 'Регистрация',
      'phoneNumber': 'Номер телефона',
      'password': 'Пароль',
      'forgotPassword': 'Забыли пароль?',
      'passwordRecoveryMock': 'Демо режим: восстановление пароля отключено.',
      'continue': 'Продолжить',
      'fullName': 'Полное имя',
      'confirmPassword': 'Подтвердите пароль',
      'createAccount': 'Создать аккаунт',
      'passwordMismatch': 'Пароли не совпадают',
      'unexpectedError': 'Произошла непредвиденная ошибка. Попробуйте ещё раз.',
      'needAccount': 'Нет аккаунта? ',
      'registerNow': 'Зарегистрируйтесь',
      'haveAccount': 'Уже есть аккаунт? ',
      'loginInstead': 'Войти',
      'changePassword': 'Изменить пароль',
      'oldPassword': 'Старый пароль',
      'newPassword': 'Новый пароль',
      'confirmNewPassword': 'Подтвердите новый пароль',
      'passwordUpdated': 'Пароль успешно обновлён',
      'save': 'Сохранить',
      'refresh': 'Обновить',
      'notifications': 'Уведомления',
      'homeGreeting': 'Добро пожаловать!',
      'ratingWithValue': 'Рейтинг: {rating}',
      'orderTaxi': 'Заказать такси',
      'sendDelivery': 'Отправить доставку',
      'activeOrders': 'Активные заказы',
      'noActiveOrders': 'Нет активных заказов. Создайте новый!',
      'recentOrders': 'Недавние заказы',
      'taxiOrder': 'Такси',
      'deliveryOrder': 'Доставка',
      'status_pending': 'Ожидание',
      'status_active': 'В пути',
      'status_completed': 'Завершён',
      'status_cancelled': 'Отменён',
      'phoneNumberShort': 'Тел',
      'editProfile': 'Редактировать профиль',
      'changePhoto': 'Обновить фото профиля',
      'refreshProfile': 'Обновить профиль',
      'selectImage': 'Выбрать из галереи',
      'noImageSelected': 'Фото не выбрано',
      'uploadPhoto': 'Загрузить фото',
      'photoUpdated': 'Фото профиля обновлено',
      'language': 'Язык',
      'darkMode': 'Тёмная тема',
      'darkModeDescription': 'Переключить интерфейс на тёмный режим',
      'driverMode': 'Режим водителя',
      'driverModeDescription':
          'Принимайте заказы и зарабатывайте. После одобрения откроется панель водителя.',
      'switchToDriver': 'Перейти в режим водителя',
      'applicationPending': 'Заявка рассматривается',
      'becomeDriver': 'Стать водителем',
      'driverBalance': 'Ваш баланс: {balance} сум',
      'logout': 'Выйти',
      'home': 'Главная',
      'orders': 'Заказы',
      'profile': 'Профиль',
      'ordersTitle': 'Заказы',
      'activeTab': 'Активные',
      'historyTab': 'История',
      'noHistory': 'История пуста. Создайте заказ!',
      'orderDetails': 'Детали заказа',
      'fromLocation': 'Откуда',
      'toLocation': 'Куда',
      'price': 'Стоимость',
      'cancelReason': 'Причина отмены',
      'cancelledByUser': 'Отменено пользователем',
      'orderCancelled': 'Заказ отменён',
      'cancelOrder': 'Отменить заказ',
      'pickupLocation': 'Точка отправления',
      'pickupAddress': 'Точный адрес (карта)',
      'dropoffAddress': 'Адрес прибытия (карта)',
      'region': 'Регион',
      'district': 'Район / город',
      'dropLocation': 'Точка прибытия',
      'tapToPickOnMap': 'Нажмите, чтобы выбрать на карте',
      'detectingLocation': 'Определяем местоположение...',
      'passengers': 'Пассажиры',
      'fullCar': 'Полная машина',
      'passengersCount': '{count} пассажира',
      'date': 'Дата',
      'timeRange': 'Диапазон времени',
      'scheduledTime': 'Запланированное время',
      'optionalNote': 'Дополнительная заметка',
      'noteHint': 'Например: Позвоните, когда приедете',
      'estimatedPrice': 'Примерная стоимость',
      'fillInfoForPrice': 'Укажите данные, чтобы рассчитать стоимость',
      'priceUnspecified': 'Не указано',
      'confirmOrder': 'Подтвердить заказ',
      'orderSummary': 'Итоги заказа',
      'note': 'Заметка',
      'noNote': 'Без заметки',
      'sendOrder': 'Отправить заказ',
      'orderSentTitle': 'Заказ отправлен',
      'orderSentDescription': 'Наши операторы скоро свяжутся с вами. Спасибо!',
      'pickOnMap': 'Выбор на карте',
      'selectedAddress': 'Выбранный адрес',
      'searchingAddress': 'Определяем адрес...',
      'confirmLocation': 'Подтвердить адрес',
      'useCurrentLocation': 'Использовать текущее местоположение',
      'locationPermissionDenied': 'Предоставьте доступ к геолокации',
      'locationUnavailable': 'Не удалось определить местоположение',
      'enableLocationServices': 'Включите службы геолокации на устройстве',
      'orderId': 'Номер заказа',
      'backHome': 'На главную',
      'senderInfo': 'Отправитель',
      'receiverInfo': 'Получатель',
      'receiverPhone': 'Телефон получателя',
      'packageType': 'Тип посылки',
      'document': 'Документ',
      'box': 'Коробка',
      'luggage': 'Багаж',
      'valuable': 'Ценные вещи',
      'other': 'Другое',
      'confirmDelivery': 'Подтвердить доставку',
      'deliverySummary': 'Итоги доставки',
      'sender': 'Отправитель',
      'receiver': 'Получатель',
      'deliverySentTitle': 'Доставка отправлена',
      'deliverySentDescription':
          'Заказ отправлен водителям. Следите за статусом.',
      'driverApplication': 'Заявка водителя',
      'driverApplicationSubtitle':
          'Заполните данные, чтобы начать работать водителем.',
      'carModel': 'Марка авто',
      'carNumber': 'Госномер',
      'driverLicenseUpload': 'Загрузите фото прав',
      'mockUploadSuccess': 'Файл для примера загружен (демо).',
      'uploadPlaceholder': 'Загрузить файл',
      'submitApplication': 'Отправить заявку',
      'fillAllFields': 'Заполните все поля',
      'applicationSentTitle': 'Заявка отправлена',
      'applicationSentDescription':
          'Мы получили вашу заявку. Одобрение займёт пару минут.',
      'driverDashboard': 'Панель водителя',
      'currentBalance': 'Текущий баланс',
      'withdraw': 'Вывести',
      'todayStats': 'Статистика за день',
      'ordersCount': '{count} заказ(ов)',
      'monthStats': 'Статистика за месяц',
      'incomingOrders': 'Новые заказы',
      'newTaxiOrders': 'Новые заказы такси',
      'newDeliveryOrders': 'Новые заказы доставки',
      'orderHistory': 'История заказов',
      'noPendingOrders': 'Новых заказов нет.',
      'noActiveDriverOrders': 'Нет активных заказов.',
      'viewHistory': 'Посмотреть историю',
      'withdrawMock': 'Демо режим: вывод средств недоступен.',
      'close': 'Закрыть',
      'completedOrders': 'Завершённые заказы',
      'acceptTimer': 'Осталось времени: {time}',
      'acceptOrder': 'Принять заказ',
      'orderAccepted': 'Заказ принят',
      'completeOrder': 'Завершить заказ',
      'orderCompleted': 'Заказ завершён',
      'orderExpired': 'Заказ устарел',
      'orderIdLabel': 'Номер заказа: {id}',
      'markAllRead': 'Отметить все как прочитанные',
      'notifDriverApplication': 'Заявка водителя получена.',
      'notifDriverApproved': 'Поздравляем! Вы одобрены как водитель.',
    },
  };

  Locale get locale => appLocale.locale;

  String tr(String key) {
    final bundle = _localizedValues[appLocale];
    if (bundle == null) {
      return key;
    }
    return bundle[key] ?? _localizedValues[AppLocale.uzLatin]![key] ?? key;
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (supported) =>
          supported.languageCode == locale.languageCode &&
          (supported.scriptCode == null ||
              supported.scriptCode == locale.scriptCode),
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    final resolvedLocale = _resolveLocale(locale);
    return SynchronousFuture(AppLocalizations(resolvedLocale));
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;

  AppLocale _resolveLocale(Locale locale) {
    for (final supported in AppLocale.values) {
      final target = supported.locale;
      final sameLanguage = target.languageCode == locale.languageCode;
      final sameCountry =
          target.countryCode == null ||
          locale.countryCode == null ||
          target.countryCode == locale.countryCode;
      final sameScript =
          target.scriptCode == null ||
          locale.scriptCode == null ||
          target.scriptCode == locale.scriptCode;

      if (sameLanguage && sameCountry && sameScript) {
        return supported;
      }
    }
    return AppLocale.uzLatin;
  }
}
